# renderdoctools/core.py
"""RenderDoc script execution engine.

Locates the bundled RenderDoc, generates temp analysis scripts,
executes them via qrenderdoc --python, and parses JSON output.
"""
from __future__ import annotations

import json
import os
import subprocess
import sys
import tempfile
from pathlib import Path

# Workspace root: parent of the renderdoctools/ package
WORKSPACE_ROOT = Path(__file__).resolve().parent.parent

# Directory containing template scripts
SCRIPTS_DIR = Path(__file__).resolve().parent / "scripts"


def find_renderdoc() -> Path:
    """Locate bundled qrenderdoc.exe. Raises FileNotFoundError if missing."""
    qrd = WORKSPACE_ROOT / "tools" / "renderdoc" / "qrenderdoc.exe"
    if not qrd.is_file():
        raise FileNotFoundError(
            "RenderDoc not found at %s\n"
            "Download RenderDoc_1.43_64.zip from renderdoc.org and "
            "extract to tools/renderdoc/" % qrd
        )
    return qrd


def run_script(
    script_name: str,
    capture_path: str,
    config: dict | None = None,
    timeout: int = 120,
) -> dict:
    """Execute a RenderDoc analysis script and return parsed JSON output."""
    qrd = find_renderdoc()
    config = config or {}

    with tempfile.TemporaryDirectory(prefix="rdtools_") as tmpdir:
        tmpdir = Path(tmpdir)
        output_path = tmpdir / "output.json"
        config_path = tmpdir / "config.json"
        script_path = tmpdir / "script.py"

        full_config = {
            "capture": str(Path(capture_path).resolve()),
            "output": str(output_path),
            **config,
        }
        config_path.write_text(json.dumps(full_config))

        template_path = SCRIPTS_DIR / (script_name + ".py")
        if not template_path.is_file():
            raise FileNotFoundError("Script template not found: %s" % template_path)

        base_header = (SCRIPTS_DIR / "_base_header.py").read_text()
        template_body = template_path.read_text()

        full_script = (
            "# Generated by renderdoctools -- do not edit\n"
            "_CONFIG_PATH = '%s'\n\n" % config_path.as_posix()
            + base_header
            + "\n"
            + template_body
        )
        script_path.write_text(full_script)

        result = subprocess.run(
            [str(qrd), "--python", str(script_path)],
            capture_output=True,
            text=True,
            timeout=timeout,
        )

        if not output_path.is_file():
            err = result.stderr.strip() if result.stderr else "No output produced"
            raise RuntimeError(
                "Script '%s' failed (exit %d): %s"
                % (script_name, result.returncode, err)
            )

        return json.loads(output_path.read_text())


def format_table(rows: list[dict], columns: list[str]) -> str:
    """Format a list of dicts as an aligned text table."""
    if not rows:
        return "(no results)"

    widths = {c: len(c) for c in columns}
    for row in rows:
        for c in columns:
            val = str(row.get(c, ""))
            widths[c] = max(widths[c], len(val))

    header = "  ".join(c.ljust(widths[c]) for c in columns)
    sep = "  ".join("-" * widths[c] for c in columns)
    lines = [header, sep]

    for row in rows:
        line = "  ".join(str(row.get(c, "")).ljust(widths[c]) for c in columns)
        lines.append(line)

    return "\n".join(lines)
